### ISSUE TITLE
Unfound Syscall tests

### ISSUE THREAD

**Issue by Yaxuan-w** [Lind-Project/safeposix-rust#174]
Here're syscalls I couldn't find corresponding tests under safeposix/tests folder:

- fstatfs
- mmap
- munmap
- getppid
- getpid
- flock
- epoll_create
- epoll_ctl
- epoll_wait
- pipe2
- getifaddrs

**Comment by rennergade** [comment]
We probably don't want to add mmap/mumap or getifaddrs since theyre mostly handled elsewhere. @kpan2034 is also currently working on flock (and should also add a safeposix test with it).

The rest of them should have tests here I believe. @Yaxuan-w @yizhuoliang can you guys add these over the next week?
